---
title: "CGC"
editor: 
  markdown: 
    wrap: sentence
---

The CGC is the Centre for Genomics and Cloning.
They are a worldwide institute with a focus on healthcare.
They hope to fix all the world's ailments with genetic engineering and if that doesn't work they clone new body parts.

Although a lot of their bespoke treatment is too expensive for normal citizens a lot of their breakthroughs have been adopted throughout the industry.
UNknown to the public, the company was inspired by the mutations in the DOT and create their own mutants for various purposes.

## CGC SCIENTIST {#scientist}

(2 HP, CHOKE 4: Consumes their CGC serum)

- Lab coat
- Lab book full of encrypted jargon
- Intelligent individual with imposter syndrome
- CGC serum (1 use)

__ENGAGED:__ Science is the greatest calling in the world and the greatest calling in science is from CGC.
Altering and creating new life, the possibility is endless.
The CGC scientist loves their work and hates the boundaries set by society and ethics.
CGC frequently pushes and breaks these boundaries.
With the right equipment and price the CGC scientist can swap a character's trait for any other.

## CGC SECURITY {#security}

(3 HP, 1D6 appear)

- Bioresonance stun rifle (NON-LETHAL)
- Cattle prod (PRIMAL-FEAR)
- Combat knife (1D6 DAMAGE)
- Net gun (1 use)
- Heavy riot shield (2 ARMOR, equip as weapon)
- Knife and bite proof clothing (1 ARMOR)
- Grim face with bite and claw scars

__KEEPERS:__ Although the security is used to stop intruders their primary purpose is to keep test subjects inside.
Their frequent handling of the various mutated animals and clones have left them scarred and hardened to force.
CGC SECURITY do not want to harm anyone or anything, preferring to capture.

__NON-LETHAL__ weapon tag: Does not deal DAMAGE; has a 3-in-1D6 chance to knock unconscious on a success. ([F:UE](https://claymorerpgs.itch.io/fist))

__PRIMAL-FEAR__ weapon tag: When used on animals it will induce fear & obedience. However, it has a 1-in-1D6 chance of enraging the animal instead.

## CGC serum {#cgc_serum}

A temporary super soldier serum.
The consumer gains +1 to all attributes, +1D6 health, and 1 ARMOR from thickened skin.
After ten minutes the character's stats and health are returned to normal and they become unconscious for 1 hour.

## CGC body serum {#cgc_body_serum}

A super soldier serum.
The consumer gains +1 to the FORCEFUL and REFLEXIVE attributes.
However, they gain -1 to the TACTICAL and CREATIVE attributes.

## CGC mind serum {#cgc_mind_serum}

A super scientist serum.
The consumer gains +1 to the TACTICAL and CREATIVE attributes.
However, they gain -1 to the FORCEFUL and REFLEXIVE attributes.

## FEMALE HORSESHOE CRAB MUTANT {#female_horseshoe_crab_mutant}

(4 HP, 1D6 appear)

- Blade arms (1D6 DAMAGE)
- Carapace (1 ARMOR)
- A 1.4 metre tall horseshoe crab in a humanoid shape
- Back and head lined with photoreceptors

__BLOOD-DONOR:__ These MUTANTS were created by genetically engineering Horseshoe crabs.
Created so their precious blood can be harvested, to help in the testing of vaccines.
It contains tetrodotoxin, a potent neurotoxin which used correctly can relieve pain of cancer-associated pain.
Anyone who consumes the blood or flesh of the FEMALE HORSESHOE CRAB MUTANT will die.

## MALE HORSESHOE CRAB MUTANT {#male_horseshoe_crab_mutant}

(2 HP, 3D6 appear)

- Small claw (1D6-3 DAMAGE, ignore negative DAMAGE)
- Carapace (1 ARMOR)
- A 80cm long horseshoe crab in a humanoid shape
- Back and head lined with photoreceptors

__CLINGER:__ These MUTANTS have two purposes.
One male clings onto a female to fertilise its eggs.
The males have been engineered without tetrodotoxin, and to be particularly tasty. 
Spare males are sold by CGC for meat.
Consuming the meat of one MALE HORSESHOE CRAB MUTANT will heal +1D6 HP as long as it is properly prepared and cooked.

## BROODING HORSESHOE CRAB MUTANT {#brooding_horseshoe_crab_mutant}

(15 HP)

- Large claws (1D6 + 1 DAMAGE)
- Black carapace with deep red cracks and star like eyes lining it (2 ARMOR)
- A 3 metre tall humanoid horse shoe crab
- Regularly releasing a clutch of eggs
- Covered by MALE HORSESHOE CRAB MUTANTS

__BROODING:__ This creature is favoured by all four of the Primeval deities.
A keen intellect from Nyxmera and strength from Tartarus.
It is able to spawn an abundance of life from Gaia.
Proteus allows it to control all its children like one body of water as a hive mind.

__SUMMON (BOSS MOVE):__ With a psychic brain blast it summons 3D6 FEMALE HORSESHOE CRAB MUTANT.
