---
title: "Dr. Petra Pufferfsih"
editor: 
  markdown: 
    wrap: sentence
---

__UNDER CONSTRUCTION__

Dr. Petra Pufferfish is the Primeval Polytheist and a super villain.
She is the only living being favoured by all the Primeval Deities.
She is especially liked by Gaia, the deity of life and unity.
Her plans involve the subjugation of the world so it may finally be united under her rule.
Many follow her cause.
They perceive her connection to all the deities as a sign of righteousness.
Her chief lieutenants are Poutine, Pudding, and Mango.

As well as being a super villain, Petra is also a super scientist.
She is pedantic and hates acronyms, she won't pronounce them correctly out of disrespect.
She loves long and descriptive names for her machines and harshly criticises her lieutenants when they try to use acronyms.
Curiously she dislikes the arbitrary nature of people's names and will frequently use only the first syllable when referring to people.
Of course she demands all her minions to use her full name, Dr. Petra Pufferfish.