---
title: "Camera Obscura"
editor: 
  markdown: 
    wrap: sentence
---

Camera Obscura are a bounty hunter company that deal in "Captures" & "Negatives" for private clients.
"Captures" involve kidnapping the target and "Negatives" are assassinations.
Agents of Camera Obscura are known as shutterbugs.

The company has 3 major rules:

1. Do not kill, harm, or kidnap any civilians except the target during a mission unless the client allows it.
2. Do not kill, harm, or kidnap any other Camera Obscura shutterbugs. This is important as Camera Obscura will normally send multiple shutterbugs for one mission, only paying out to one individual/group.
3. Non-shutterbug mercenaries, bodyguards, and vigilantes are fair game to eliminate.

These rules lead to team ups and rivalries aplenty.

## THE ANTIDOTER {#the_antidoter}

(4 HP, CHOKE 4: ingest a fake cyanide pill which mimics a state of death for 12 hours)

- Steak knife (3 DAMAGE)
- Disguised as waiting staff or caterers
- Official work documents
- Fog machine with airborne antidote
- Antidote 

__CONTAMINATOR:__ Poisoning a target's food is difficult, suspicious, and error prone. Poisoning everyone's food is a cinch. The ANTIDOTER uses a special 2 part poison they have an antidote for. One part is harmless. Consuming both parts within four hours of each other causes a deadly heart attack within a few minutes. The poisons are undetectable but a special antidote administered after the first or second part will prevent death.

__PSIONIC PIPES (BOSS MOVE):__ Only works on individuals who have consumed at least one part of the poison. Attracts non-targets and repels target/s. This requires a lot of concentration whilst they are maintaining this effect. Trained individuals may be able to notice this effect. Once everyone is in place they will use their fog machine to spread the antidote to non targets.

## THE KING {#the_king}

(4 HP, CHOKE 2: Lifts midas touch curse and barters for mercy with pilfered goods)

- Deck of cards
- Lock picking tools
- Great sleight of hand and distraction skills
- Covered in pilfered jewellery
- Will not wear gold
- Simple but stylish dress
- Real identity is [

__CONCEITED:__ Their real identity is [Queen Hermodike II/Damodice](https://en.wikipedia.org/wiki/Hermodike_II), the wife of [King Midas](https://en.wikipedia.org/wiki/Midas). 
Turned into gold by her husband she was changed back by Nyxmera in the modern day.
Their rage towards their late husband means they only target the rich and greedy. 
They are vain, prideful, and beautiful. 
Using a portfolio of personaes they have infiltrated into various upper social circles. 
They can't help themselves from stealing jewellery and immediately wearing it. 
Their overbearing charisma stops the vast majority from questioning or confronting THE KING about this. 

__MIDAS TOUCH (BOSS MOVE):__ They can imbue one gold item and one person with the Midas curse. THE KING must touch the gold and person at the same time to cast the curse. If and when the cursed person willingly touches the cursed gold the victim will permanently turn into solid gold. Any other person touching the cursed gold and/or person during the transformation will also turn to gold. After transformation is complete the curse is complete and the gold will not convert anymore people.

## THE SILHOUETTE {#the_silhouette}

(6 HP)

- [FAMAS](https://en.wikipedia.org/wiki/FAMAS) assault rifle (1D6+1 DAMAGE, COLLAPSIBLE)
- Trucker gear
- Hidden bulletproof vest (1 ARMOR)
- Disguised truck with gear for shadow clones in hold
- No visible shadow

__SHADOW-PLAY:__ This shutterbug is cautious and never gets their own hands dirty. Instead, they always leave Captures and Negatives to their [SILHOUETTE SHADOW CLONES](#silhouette_shadow_clone). They park a good distance away orchestrating the clones via their truck's radio system, speaking in trucker terminology as code. If the missions goes south they will calmly retreat.

__SHADOW CAST (BOSS MOVE)__: Creates 4 [SILHOUETTE SHADOW CLONES](#silhouette_shadow_clone). They have the memories and skill of the caster and will follows its commands. Unfortunately, shadow clones appear with no clothes and gear. For full effect they need to be used in advance to gear up. The clones can only be summoned and maintained on moonlit nights.

## SILHOUETTE SHADOW CLONE {#silhouette_shadow_clone}

(1 HP)

- [FAMAS](https://en.wikipedia.org/wiki/FAMAS) assault rifle (1D6+1 DAMAGE)
- Heavy riot shield (2 ARMOR, equip as weapon)
- Deep black tactical gear (1 ARMOR)
- Radio headset

__IMMATERIAL__: These beings are shadows given life. Their only desire is to complete their mission and become one with the darkness again. When they die they leave only their gear behind. They can die at will so will never be captured.
