---
title: "Catalog"
editor: 
  markdown: 
    wrap: sentence
---


## Link to all units

- Nyxmera
  - Followers
    - [Sun of Nyxmera](/Nyxmera/Followers.qmd#sun_nyxmera)
    - [Mouth of Nyxmera](/Nyxmera/Followers.qmd#mouth_nyxmera)
  - Troops
    - [Nyxmera trooper](/Nyxmera/Troops.qmd#nyxmera_tropper)
    - [Nyxmera Light Trooper](/Nyxmera/Troops.qmd#nyxmera_light_tropper)
    - [Nyxmera Dark Trooper](/Nyxmera/Troops.qmd#nyxmera_dark_trooper)
  - Starvatars
    - [Starvatar of Nyxmera](/Nyxmera/Starvatars.qmd#starvatar)
- Tartarus
  - Followers
    - [Dotter of Tartarus](/Tartarus/Followers.qmd#Dotter)
    - [ELDER DOTTER OF TARTARUS](/Tartarus/Followers.qmd#elder_dotter)
  - DOT raiders
    - [TARTARUS RAIDER](/Tartarus/DOT_raiders.qmd#raider)
    - [TARTARUS MUTANT](/Tartarus/DOT_raiders.qmd#tartarus_mutant)
    - [TARTARUS FIRE WARRIOR](/Tartarus/DOT_raiders.qmd#fire_warrior)
    - [TARTARUS MAGNETIC SLINGER](/Tartarus/DOT_raiders.qmd#magnetic_slinger)
    - [Scrapper](/Tartarus/DOT_raiders.qmd#scrapper)
  - Kraken
    - [KRAKEN SECURITY GUARDS](/Tartarus/Kraken.qmd#kraken_guard)
    - [Kraken private contractors](/Tartarus/Kraken.qmd#kraken_contractors)
  - Taloes
    - [METAL ORE TALOS](/Tartarus/Taloes.qmd#ore_talos)
    - [OBSIDIAN LAVA TALOS](/Tartarus/Taloes.qmd#obsidian_talos)
    - [LITHIUM TALOS](/Tartarus/Taloes.qmd#litium_talos)
    - [Radiactive Gem Talos](/Tartarus/Taloes.qmd#rad_talos)
- Gaia
  - TAG
    - [TAG Protestor](/Gaia/TAG.qmd#tag_protestor)
    - [TAG Eco Fighter](/Gaia/TAG.qmd#tag_fighter)
    - [TAG Hacker](/Gaia/TAG.qmd#tag_hacker)
    - [TAG leader](/Gaia/TAG.qmd#tag_leader)
