---
title: "History"
---

WWII ends with the nuclear bombing of Japan, unleashing kaiju from the DOT. The population of Japan is evacuated. Thankfully the Kaiju are kept land bound on the main Japan island by the powers of Gaia & Proteus.

Due to this Nuclear weapons are banned by world governments leading to uneasy peace. This lead to the formation of major superpowers.

-   [The Biways](/History/Biways.qmd): England, Scotland, Ireland, Wales, Greenland, Iceland, and other smaller islands.

-   [USA](/History/USA.qmd): United States of America. The number one superpower consisting of all the Americas

-   [ERA](/History/ERA.qmd): European & Russian Alliance. Europe & Russia.

-   [CAC](/History/CAC.qmd): Coalition of African Countries. All of Africa.

-   [SAE](/History/SAE.qmd): Supreme Asian Empire. All Asian countries except Russia with India & China co-leading uneasily.

-   [Oceania](/History/Oceania.qmd): Australia, New Zealand, Tasmania, and other small islands.

-   [The Moon](/History/The_moon.qmd): Settled primarily by Japanese refugees.
