---
title: "Kraken"
editor: 
  markdown: 
    wrap: sentence
---

Kraken is a large energy and mining corporation. They deal in oil and nuclear power. They also mine for oil, nuclear ores, metal ores, and gems. The CEO is Marian Dullcoin (Elder Dotter of Tartarus).

### Kraken security guard {#kraken_guard}

(4 HP, 2 appear)

- Bioresonance disruptor rifle (1D6+1 DAMAGE, BIOLOGICAL)
- Hazard foam grenade launcher, able to fill holes, quench fires, block radiation, and slow down foes (3 uses)
- Hazard suit (1 ARMOR)
- Hard hat (accessory)
- High vis jacket
- Half a key card each
- Prone to ask ridiculous either or questions with their buddy (“Would you rather fight a horse sized duck or 100 duck sized horses?”)

__SAFETY BUDDIES:__ Two guards make a whole. For security they are each given half of any security passes so both must be present, stopping 1 captured/pilfered guard from allowing breaches. They can and will use their hazard foam grenades to subdue trespassers.

__BIOLOGICAL__ weapon trait: Only damages biological beings. Cannot damage structures, vehicles, or chemicals. 

***

### Kraken private contractor {#kraken_contractors}

(4 HP, 1D6 appear)

- Heckler & Koch MP5K submachine gun (1D6 DAMAGE)
- Combat knife (1D6 DAMAGE)
- Kevlar military vest (1 ARMOR)
- Battering ram (1D6 DAMAGE)
- Kept in reserve until combat starts
- Trigger happy swat wannabes

__CQC:__ Rush into close quarter combat as they want the bonus for killing any enemies. With their battering ram they can break through any unbarricaded hinged door with abandon.