---
title: "Units"
editor: 
  markdown: 
    wrap: sentence
---

## Nyxmera

### Meteorite of Nyxmera

Imbued with the sight of Nyxmera it can be used to re-roll one of the two dice used for any TACTICAL roll. 
Four meteorites can be used to change one of the 2 dice to a result of 6.
Once used it shatters into pure light.

## Tartarus

### Rock of Tartarus

Imbued with the power of Tartarus it can be used to re-roll one of the two dice used for any FORCEFUL roll. 
Four rocks can be used to change one of the 2 dice to a result of 6.
Once used it crumbles into inert gravel.

## Proteus

### Water orb of Proteus

Imbued with the flow of Proteus it can be used to re-roll one of the two dice used for any REFLEXIVE roll. 
Four water orbs can be used to change one of the 2 dice to a result of 6.
Once used it evaporates into steam.

## Gaia

### Heart of Gaia

Imbued with the life of Gaia it can be used to re-roll one of the two dice used for any CREATIVE roll. 
Four hearts can be used to change one of the 2 dice to a result of 6.
Once used it dissolves into blood.
