---
title: "Units"
editor: 
  markdown: 
    wrap: sentence
---

## Nyxmera

### Suns of Nyxmera

- [SUN OF NYXMERA](/Nyxmera/Suns.qmd#sun_nyxmera)
- [MOUTH OF NYXMERA](/Nyxmera/Suns.qmd#mouth_nyxmera)

### Troops
    
- [NYXMERA TROOPER](/Nyxmera/Troops.qmd#nyxmera_tropper)
- [NYXMERA LIGHT TROOPER](/Nyxmera/Troops.qmd#nyxmera_light_tropper)
- [NYXMERA DARK TROOPER](/Nyxmera/Troops.qmd#nyxmera_dark_trooper)

### Camera Obscura

- [THE ANTIDOTER](/Nyxmera/Camera_Obscura.qmd#the_antidoter)
- [THE KING](/Nyxmera/Camera_Obscura.qmd#the_king)
- [THE SILHOUETTE](/Nyxmera/Camera_Obscura.qmd#the_silhouette)
- [SILHOUETTE SHADOW CLONE](/Nyxmera/Camera_Obscura.qmd#silhouette_shadow_clone)
 
### Starvatars

- [STARVATAR OF NYXMERA](/Nyxmera/Starvatars.qmd#starvatar)
- [PURPLE MOON OF NYXMERA](/Nyxmera/Starvatars.qmd#purple_moon)

## Tartarus

### Dotters of Tartarus

- [DOTTER OF TARTARUS](/Tartarus/Dotters.qmd#Dotter)
- [ELDER DOTTER OF TARTARUS](/Tartarus/Dotters.qmd#elder_dotter)

### DOT raiders
    
- [TARTARUS RAIDER](/Tartarus/DOT_raiders.qmd#raider)
- [TARTARUS MUTANT](/Tartarus/DOT_raiders.qmd#tartarus_mutant)
- [TARTARUS FIRE WARRIOR](/Tartarus/DOT_raiders.qmd#fire_warrior)
- [TARTARUS MAGNETIC SLINGER](/Tartarus/DOT_raiders.qmd#magnetic_slinger)
- [SCRAPPER](/Tartarus/DOT_raiders.qmd#scrapper)

### Kraken

- [KRAKEN SECURITY GUARDS](/Tartarus/Kraken.qmd#kraken_guard)
- [KRAKEN PRIVATE CONTRACTOR](/Tartarus/Kraken.qmd#kraken_contractors)
- [KRAKEN SLAGGER](Tartarus/Kraken.qmd#kraken_slagger)

### Taloes

- [LITHIUM TALOS](/Tartarus/Taloes.qmd#litium_talos)
- [METAL ORE TALOS](/Tartarus/Taloes.qmd#ore_talos)
- [OBSIDIAN LAVA TALOS](/Tartarus/Taloes.qmd#obsidian_talos)
- [RADIOACTIVE GEM TALOS](/Tartarus/Taloes.qmd#rad_talos)

### Kaiju

- [SCORPIUS](/Tartarus/Kaiju.qmd#scorpius)
- [PYTHON](/Tartarus/Kaiju.qmd#python)

## Proteus

### Proteans

- [PROTEAN](/Proteus/Proteans.qmd#protean)
- [PROTEAN CAPTAIN](/Proteus/Proteans.qmd#protean_captain)

### Triton & Delta

- [TRITON & DELTA SELLER](/Triton_n_Delta.qmd#triton_delta_seller)
- [TRITON & DELTA ENFORCER](/Proteus/Triton_n_Delta.qmd#triton-delta-enforcer)

### Refraction Sports

- [PROTEAN SURFER](/Proteus/Refraction_Sports.qmd#protean-surfer)
- [PROTEAN SNOWBOARDER](/Proteus/Refraction_Sports.qmd#protean-snowboarder)

### Poutine the Hyperborean

- [POUTINE THE HYPERBOREAN](/Proteus/Poutine_the_hyperborean.qmd#poutine)
- [SNOWBALL SWARM](/Proteus/Poutine_the_hyperborean.qmd#snowball_swarm)
- [CYBORG ORCA](/Proteus/Poutine_the_hyperborean.qmd#cyborg_orca)
- [ORCA WRANGLER](/Proteus/Poutine_the_hyperborean.qmd#orca_wrangler)
- [CYBORG POLAR BEAR](/Proteus/Poutine_the_hyperborean.qmd#cyborg_polar_bear)
- [POLAR BEAR RIDER](/Proteus/Poutine_the_hyperborean.qmd#cyborg_polar_bear_rider)
- [POUTINE RIFLEMAN](/Proteus/Poutine_the_hyperborean.qmd#poutine_rifleman)

## Gaia

### TAG

- [TAG PROTESTOR](/Gaia/TAG.qmd#tag_protestor)
- [TAG ECO FIGHTER](/Gaia/TAG.qmd#tag_fighter)
- [TAG HACKER](/Gaia/TAG.qmd#tag_hacker)
- [TAG LEADER](/Gaia/TAG.qmd#tag_leader)

### Cult of Skyuss

- [INCUBATOR CULTIST OF SKYUSS](/Gaia/Skyuss.qmd#skyuss_incubator)
- [MUTATED CULTIST OF SKYUSS](/Gaia/Skyuss.qmd#skyuss_mutated_cultist)
- [DEACON OF SKYUSS](/Gaia/Skyuss.qmd#skyuss_deacon)
- [PREMATURE SNOW WORM](/Gaia/Skyuss.qmd#premature_worm)
- [JUVENILE SNOW WORM](/Gaia/Skyuss.qmd#juvenile_worm)
- [ADULT SNOW WORM](/Gaia/Skyuss.qmd#adult_worm)

## USA

### USA Navy

- [CYBORG DOLPHIN](/History/USA_navy.qmd#cyborg_dolphin)
- [HUMPBACK WHALE SUBMERSIBLE](/History/USA_navy.qmd#humpback_sub)
- [HUMPBACK WHALE WEAPONS PLATFORM](/History/USA_navy.qmd#humpback_plat)

## ERA

### ERA Navy

- [CYBORG COLOSSAL SQUID](/History/ERA_navy.qmd#cyborg_colossal_squid)
