---
title: "Weapon tags"
editor: 
  markdown: 
    wrap: sentence
---

All the weapon tags for this website.

## BIOLOGICAL

Only damages biological beings. Cannot damage structures, vehicles, or chemicals.

## DIG

Able to dig through solid rock, allowing traversal.

## DOOR-BREACHER 

Can be used to break through any locked or unlocked hinged door that is not barricaded.

## ENERGY-HUNGRY

Requires a a large amount of energy to function.

## GIGANTIC

Far too large and heavy to be held as a weapon for normal sized people.

## MELT

Weapon (melee) or projectiles (firearm) are made from a non-metallic substance that will melt over time. DAMAGE NEGATION by ARMOR is doubled for this weapon.

## PERCUSSIVE-MAINTENANCE

Once per mission this weapon can be used to fix a malfunctioning device. This includes, but is not limited to, jammed or overheated weapons, stuck elevators, stalled vehicles, and a fuzzy television.

## PRIMAL-FEAR

When used on animals it will induce fear & obedience. However, it has a 1-in-1D6 chance of enraging the animal instead.

## SHOULDER-CRUSHER

When fired it has a 1-in-1D6 chance of breaking the user’s shoulder and inflicting 1 DAMAGE to the user.


