---
title: "TAG: The Arrows of Gaia"
editor: 
  markdown: 
    wrap: sentence
---

Climate change and environmental destructions are existential threats to all life on earth.
TAG are an organisation of eco warriors.
Primarily they carry out peaceful protests and other activities that benefit the environment.

Their slogan is "you're it" . ON one hand referring to those they are targeting or will target next. And on the other a call of action for everyone else to join the environmental fight.

Some members form more radical groups that sabotage environmentally damaging facilities such as oil pipes, chemical production companies, etc.

### TAG Protestor {#tag_protestor}

(3 HP, CHOKE 5: Scatter and hide) 

- Placard & leaflets
- Unassuming clothing with a cap
- Snacks and drinks
- Loud and proud

__CONVICTED:__ Many protesters have been previously imprisoned for their convictions. 
They can be majorly disruptive but people will only deal with them if given orders they can't refuse.
A touch from a group of protesters will cause most to join the protest. Many that join this way leave with a very foggy memory of it all.

***

### TAG Eco Fighter  {#tag_fighter}

(4 HP, 1D6 appear)

- [Winchester Model 1200](https://en.wikipedia.org/wiki/Winchester_Model_1200) Pump-action shotgun (1D6+1 DAMAGE)
- Molotov cocktail (1D6 DAMAGE, one use)
- Hunting apparel with backpack
- Binoculars
- Normal men and women who look like hunters
- Signs of damage by industrial exploitation

__JUSTIFIED__: Eco warriors stand up for what is right.
They have been harmed by industrial chemicals or machines.
With nothing left they will put down their lives to ensure life will continue.
They will never surrender, either fighting till the end or retreating to fight another day.
Intimidation tactics never work of eco warriors.

***

### TAG Hacker {#tag_hacker}

(5 HP)

- [PB](https://en.wikipedia.org/wiki/PB_(pistol)) silenced pistol (1D6 DAMAGE)
- Hacker's axe (1D6+1 DAMAGE, ELECTRIFIED)
- Concealed bullet resistant vest (1 ARMOR)
- Hard helmet (accessory)
- Floppy disk wallet (5 uses)
- [Phreak](https://en.wikipedia.org/wiki/Phreaking) whistle
- Mobile phone and voice changer
- Lumberjack attire

__HACKED-OFF__: Society is all a farce! A game this hacker now knows how to play.
Incredible skills in hacking computers, phone lines, and social situations make them perfect agents for TAG.
However, they must be kept on a short leash as they don't hack for what is right but rather because they have been wronged.
Hackers will quickly changed side if given enough incentives in finances, safety, and comfortability.

__ELECTRIFIED__ weapon tag: Deals double DAMAGE to robots and other complex machines. Shorts out running electronics and briefly electrifies bodies of water.

__Floppy disk wallet__ item: Contains 5 floppy disks. Each disk is consumed when used to try to hack a computer system with a floppy disk input. Each disk has a single word indicating its effect; Ransom ware, Decrypt, Virus, Login, and Loop. The effect of each floppy disk is detremined by the circumstance, imagination of the players, result of relvant action roll, and the referee's decision.

***

### TAG Leader {#tag_leader}

(6 HP)

- [Steyr AUG](https://en.wikipedia.org/wiki/Steyr_AUG) assault rifle (1D6+1 DAMAGE)
- Blade of grass, sword (2D6 DAMAGE, RITUAL)
- Tactical vest (1 ARMOR)
- Enchanted wood shield (2 ARMOR, equip as weapon)
- Blowing horn, calls forth the largest nearby land animals (1 use)
- Long flowing hair framing a beautiful face
- Gentle but commanding voice

__TAMER__: Able to keep TAG fighters in line this leader is vital to TAG violent activities. 
They can tame and enlarge multiple wild creatures of the same species with the blessing of Gaia.
If the TAG Leader is killed or knocked unconscious the effect will immediately end.

__RITUAL__ weapon tag: Shatters to protect you from death once, negating lethal damage. Disintegrates afterward.
