---
title: "The Biways"
---

The British Isles, also known as the Biways, consists of England, Scotland, Ireland, Wales, Greenland, Iceland, and other smaller islands.

## Primary deity

None/agnostic

## Positives

- __Rich:__ The Biways is the financial hub of the world. The pound is the most traded and trusted currency in the world.
- __Nuclear power:__ Greenland is used for nuclear power generation to sell to the world, especially the USA.
- __Research:__ Contains many universities with leading research.


## Negatives

- __Corrupt:__ It is a great place for off shore bank accounts and laundering money. It is a haven for fugitives of other countries. As long as the fugitive has capital. Many of the world's elites and most dangerous live in the Biways, benefiting from interacting with each other.
- __Dangerous science:__ Iceland is where many dangerous scientific research is carried out is carried out by super scientists across the world.
- __Brain drain:__ The Biways is very attractive to experts across the world. This unfortunately takes away specilaists from other countries that may need them more.
