---
title: "ERA"
---

The European & Russian Alliance. Europe & Russia.

## Primary deity

The primary deity of the ERA is [Proteus](#/proteus.qmd).

## Positives

- __Free movement:__ Has a lingua franca (English). This allows lots of movement across countries therefore sharing skills and knowledge across the alliance.
- __Coastal:__ Most of their major cities are on coasts allowing most of their war torn (WWII) inner lands to be claimed by nature. This benefit's the physical and mental health of the citizens.
- __World trade:__ They are the world's port trade hub. 


## Negatives

- __Impressionable:__ They are easily swayed by the culture of other powers, primarily the USA. This means they place less value on their own cultures.
- __Low hanging fruit pickers:__ They like easy fixes and jobs even if it ends up costing them more in the long run.
- __Scarred:__ Due to the damage of WWII the power is traumatised. They do not deal well with aggression and tend to allow others to get their way when threatened. 
