---
title: "USA"
---

The United States of America. The number one power consisting of all the Americas.

## Primary deity

The primary deity of the USA is [Gaia](/gaia.qmd).

## Positives

- __Powerful:__ It is the most powerful and advanced power in the world. This leads to a comfortable way of life for many citizens.
- __Education:__ Top notch education leads to an intelligent population. All citizens learn English, Spanish and French from a young age.
- __United:__ The power is united in their ideals and are able to accomplish what they want with minimal issues.

## Negatives

- __Superiority complex:__ The USA and its citizens are confident of their superiority. They look down on other powers and cultures.
- __Group mind:__ All citizens are taught in the same way and watch the same media. They are as close to a hive mind without being connected to each other. This has lead to poor creativity and no devil's advocates.
- __Hyper capitalist:__ Believe that citizens are for the benefit of the economy.