---
title: "USA Navy"
---

The USA Navy.

## CYBORG DOLPHIN {#cyborg_dolphin}

(4 HP)

-   Spear mouth guard (1D6 DAMAGE)
-   Laser (1D6+1 DAMAGE) works in air and water
-   Cyborg armor (1 ARMOR)
-   Retractile quad legs, sharp pointed ends for safe ice travel vertically & horizontally
-   Saddle for 1 passenger
-   Translator & comms module (TCM)
-   Echolocation

**SOCIAL:** CYBORG DOLPHINS are prized due to their communication skills. Humans can orally speak with them if they connect to their TCM. However, Dolphins can only use and understand single syllable words. They will listen to their rider if they are respected and treated well.

## HUMPBACK WHALE SUBMERSIBLE {#humpback_sub}

(20 HP)

-   4 torpedoes (1D6+2 DAMAGE)
-   Sparse titanium plates (1 ARMOR)
-   Control dock mounted in front of blow hole, connected to brain of whale. Human captain controls it like a vehicle (2HP, 4 ARMOR)
-   Large hump crate on back
-   Deployable millipede like legs to get onto ground

**AMPHIBIOUS**: The true purpose of the submersible is to emerge from the waters and become a ground borne weapons platform. Once out of the water and with some time it deploys its gear from it hump crate. It retains its HP but become a HUMPBACK WHALE WEAPONS PLATFORM.

## HUMPBACK WHALE WEAPONS PLATFORM {#humpback_plat}

(20 HP)

-   Forward mounted cannons controlled by pilot (3D6+3 DAMAGE, ANTI-MATERIAL, 2 uses)
-   Fully deployed titanium plating (3 ARMOR), supports whale's weight
-   Control dock mounted in front of blow hole, connected to brain of whale. Human captain controls it like a vehicle (2HP, 4 ARMOR)
-   Deck on back with 1 ARMOR walls
-   Metal ladders on both sides towards the tail
-   One Left and one right side mounted [Ball turret](https://en.wikipedia.org/wiki/Ball_turret) (6HP, 2 ARMOR) each with 2 [M2 Browing](https://en.wikipedia.org/wiki/M2_Browning) heavy machine guns [XM214 Microgun](https://en.wikipedia.org/wiki/XM214_Microgun) (1D6+2 DAMAGE), need to be manned

**PAKICETUS:** Whales are back on land and they are packing. These armoured cetaceans get troops where they need to be by carving a path of destruction.

__ANTI-MATERIEL__ weapon tag: Deals double DAMAGE to vehicles and structures; cumbersome to carry around. ([F:UE](https://claymorerpgs.itch.io/fist))