---
title: "POPS: Possible Oil Pipe Sabotage"
editor: 
  markdown: 
    wrap: sentence
---

## Choice of mission

- Hired by Kraken (Dotters of Tartarus) to prevent sabotage by Gaians.
- Hired by TAG (Gaians) to sabotage pipeline.

3 different stations along the straight pipeline. They are situated within the [Black Forest](https://en.wikipedia.org/wiki/Black_Forest). 

## Gaian sabotaging

The team will need to hack into 3 different small stations along the pipeline.
They will be provided 4 eight inch floppy disks, 1 needed for each hack.

Two pairs of [Kraken security guards](/Tartarus/Kraken.qmd#kraken_guard) at each base. If the alarm goes off, [Kraken private contractors](/Tartarus/Kraken.qmd#kraken_contractors) will appear in SUVs, this will take a bit of time.

At the last station there will be a [Metal Ore Talos](/Tartarus/Taloes.qmd#ore_talos). It will not be alert if the alarm has not gone off.
It will never fire if the oil pipeline is in the line of fire.

### Rewards

[M1 Garand](https://en.wikipedia.org/wiki/M1_Garand) semi-automatic rifle (1D6+1 DAMAGE, MEDICAL)

__MEDICAL__ weapon tag: Once per mission, you may use this weapon to deal negative DAMAGE, healing the target.

## Kraken Defence

Defend one station from 3 waves.
The team will have access to an imprisoned TAG spy   .

The team should be encouraged to set up traps and defences.
Other plans are encouraged.
A much easier mission but will definitely involve combat.

Waves:

1. 1D6 [TAG Eco Fighters](/Gaia/TAG.qmd#tag_fighter).
2. 2D6 [TAG Eco Fighters](/Gaia/TAG.qmd#tag_fighter) & 1 [TAG Hacker](/Gaia/TAG.qmd#tag_hacker)
  - Hacker will try to hack any electronic systems from afar during attack. They may even phone the mercs to try and trick them in some way before the 2nd wave.
3. 1D6 [TAG Eco Fighters](/Gaia/TAG.qmd#tag_fighter) per FIST merc & 1 [TAG Leader](/Gaia/TAG.qmd#tag_leader).
  - All the units of this wave are riding tamed enlarged wild boars by the TAG leader's ability. They are enlarged and tamed as long as the TAG leader is conscious.
  - Enlarged boar: 4HP, 1 ARMOR, 1D6 damage from charge.
  - Wild board: 3HP, worst-of-2D6 damage damage from charge.

### Rewards

[Ruger Hawkeye](https://en.wikipedia.org/wiki/Ruger_Hawkeye) hand cannon (1D6+1 DAMAGE, QUICK-DRAW)

__QUICK-DRAW__ weapon tag: Attacks that target enemies drawing their weapons will always succeed.
