---
title: "TIDY: Terrifying Infiltration of Dump Yard"
editor: 
  markdown: 
    wrap: sentence
---

__UNDER CONSTRUCTION__

## Mission

DOT raiders charge FIST with infiltrate a dump yard. 
This is where trash, chemical, waster, and nuclear waste are disposed of by tipping it into the DOT.
These sites are heavily guarded due to the contents but also to stop raiders and creatures from reaching the surface via a dot into the DOT.

FIST are provided with a floppy disk by the DOT raiders to disable the security systems including automated turrets. However, it will only disable the Kaiju Sonic Disruption System (KSDS).

This will cause small kaiju to rush into the dunping site only to be followed by a massive kaiju. This kaiju is three giant snakes connected by a giant obsidian orb.

Double twist, this was a plan by the mooners to test out one of their mecha against a real kaiju. The KSDS will turn back on stopping further Kaiju from coming in and our FIST team will be able to pilot a mecha hidden in a skyscraper sized crate to stop the Kaiju.

This will most likely fail as the mecha is a prototype but one FIST member can self destruct the mecha followed by the rest of the team using laser triangulators on the Kaiju to call down rods from god the mooners had as a back up plan.