---
title: "History"
editor: visual
---

WWII ends with the nuclear bombing of Japan, unleashing kaiju from the DOT. The population of Japan is evacuated. Thankfully the Kaiju are kept land bound on the main Japan island by the powers of Gaia & Proteus.

Due to this Nuclear weapons are banned by world governments leading to uneasy peace. This leads to the formation of major superpowers.

-   USA: United States of America. The number one superpower consisting of all the Americas

-   CAC: Coalition of African Countries. All of Africa.

-   ERA: European & Russian Alliance. Europe & Russia.

-   SAE: Supreme Asian Empire. All Asian countries except Russia with India & China co-leading uneasily.

-   Oceania: Australia, New Zealand, Tasmania, and other small islands.

-   British Isles: England, Scotland, Ireland, Wales, Greenland, Iceland, and other smaller islands. Also known as the biway.

    -   The financial hub of the world. A great place for off shore bank accounts and laundering money.

    -   A haven for fugitives of other countries with capital.

    -   Many of the world's elites and most dangerous live here benefitting from interacting with each other.

    -   Violent crimes are not tolerated in the British isles A great place for FIST to be based but in one of the less wealthy areas (Ireland, Wales, Isle of Man, or Isle of Wight).

    -   Greenland is used for nuclear power generation to sell to the world (primarily the USA) and to keep armies stationed.

    -   Iceland is where many more dangerous scientific research is carried out.

Space travel was expedited due to the world governments working together to carry it out. The Japanese refugees took this as an opportunity to create a new home as the first settlers on the moon at the start of the 1960s. They have 2 major metropolises there called Usagi (Rabbit) and Kaguya. They specialise in combustion light-gas guns (large cannons with high velocity) and mechs. When they are ready they plan to take back Japan.
