---
title: "Nyxmera"
editor: 
  markdown: 
    wrap: sentence
---

Nyxmera is the light, literally.
All the celestial bodies are known as the eyes of Nyxmera, the sun, moons, planets and stars.
With these Nyxmera watches, they want to be entertained.

However, some think that these physical objects are Nyxmera but they are mistaken.
It is the light that comes from these that make Nyxmera.
And even though Nyxmera spans all of space it is stuck in a perpetual gaze.
No wonder it sends its avatars to Earth for some fun.

-   The two-sided deity of night and day
-   Loves extremes of good and evil, conflict, and drama
-   Followers: Suns of Nyxmera
    -   Followers include navigators, space enthusiasts, story tellers, and entertainers
-   Good factions
    -   Generally do very visible good such as disaster relief, peace keeping, good police etc.
-   Bad factions
    -   Generally do evil in the dark such as war, human trafficking
-   Best followers
    -   Those who do extreme good and evils
    -   Examples include
        -   Good cops that are also very corrupt
        -   Actors who bring joy to the public but have a dark private side

## Followers

### Sun of Nyxmera (3 HP, CHOKE 3: Stare and applaud)

- Large mobile phone
- Camera
- Binoculars
- Casual clothing with eyes in space theme

__GAWKER:__ These followers of Nyxmera act as eyes of the deity and nothing more. They mindlessly consume content and go out of their way to witness danger. They will call in further Suns of Nyxmera if they see a dangerous event possibly causing further civilian casualties.

### Mouth of Nyxmera (3 HP, CHOKE 4: Escape from current situation and lie low)

- Laser finger gun (worst of 2D6 DAMAGE)
- Hard light shard (Teleport user to a pre designated place within 1 mile, 1 use,).
- Very extravagant and bombastic
- Outwardly Friendly to friends and aggressive to enemies

__CAPRICIOUS:__ Leaders amongst the followers of Nyxmera. They tend to be high up in entertainment or politics. Always keen to cause the most drama they may be a friend of FIST one mission and then an enemy the next. They are in it for the long game and want to remain in Nyxmera’s spotlight for a long time.  They will try to create an interesting series of events for Nyxmera to watch.

## Troops

### Nyxmera trooper (3 HP, 2D6 appear)

- Semi-Auto Laser rifle (Choose 1 of 2D6 DAMAGE, 1D6 DAMAGE for other users)
- Meteor scrap metal armor (1 ARMOR)
- Rifle mounted light (Directional close range sight in the dark)
- Black and white fatigues, covered in scraps of meteor metal.

__DUALITY:__ These troopers embody the day and night extremes of Nyxmera. They will shoot allies and enemies alike with their laser rifles. When dealing damage with these they harm the target on even totals and heal the target on odd totals. Normally the referee will choose which die to use. However, if a player adds one or more WAR DICE they choose which single dice to remove from the DAMAGE.

### Nyxmera light trooper (3 HP, 1D6 appear)

- Laser shotgun (1D6 + 1 DAMAGE)
- 1D6 stun grenades (temporary blinding, one use)
- Helmet mounted lantern (close range sight in the dark)
- Meteor metal armor (2 ARMOR)
- Hard light projector (1 use)

__STEADFAST:__ These heavy troopers stand strong against the dark. They routinely use the combination of their lanterns and hard light projectors to corner enemies.

### Nyxmera dark trooper (6 HP)

- Meteor sword (1D6 + 1 DAMAGE, LIGHT)
- Night vision goggles (see at night)
- Light diffraction weave bodysuit (1 ARMOR, difficult to see)
- Shadow boots (Can teleport from one shadow to another within a range of 30 feet, 1 use)
- Deployable hard light hoverboard (accessory)

__PATIENT:__ The dark trooper will watch and stalk enemies. It will bide its time for the best opportunity to reveal itself based on how cool it would be. If it begins a fight with no backup it will take no DAMAGE from the first attack against them, doing a narly flip or trick to evade it.

## Starvatars

A Starvatar of Nyxmera is the light of a star. When it exists the star’s light can no longer be seen in the night sky as it now exists as a hard light being. Each Starvatar will take the name of its star or constellation.

They are humanoid like being made of the night sky. They are pitch black solid with twinkling lights covering their body. Their legs and arms taper down to points like the human depiction of a star on paper. Invisible digits allow them to handle anything a human could including guns.

All Starvatars of Nyxmera look nearly identical except for their heads. These are in the shape of something related to the human mythology of their star or the constellation it belongs to. On this head is one bright light, the star’s light they use as an eye. Examples of head shapes include:

- Zodiac: Leo = Lion, Cancer = Crab , Gemini = Twins, Taurus = bull, Aries = Ram, Pisces = Fish, Aquarius = water carrier, Capricorn =  Sea goat, Sagittarius = Centaur, Scorpio = scorpion, Libra = Scales, Virgo =  Maiden.
- Bear head from Ursa major and minor

Powerful Starvatars can create temporary structures made of hard light

### Stavatar of Nyxmera (9 HP)

- Starlight rifle (1D6 + 2 DAMAGE, MEDICAL)
- Starlight spear (1D6 + 2 DAMAGE, UNSTABLE)
- Hard light armor (2 ARMOR)

__SHADOWMAKER:__ The star avatar’s body is that of the night sky. The shape of its head matches the mythology of the star or constellation it comes from. Upon this head is one eye made from the light of its star. It casts a great light from its eye and body. However shadows caused by this are irrationally dark and cannot be illuminated by other lights.