---
title: "Tartarus"
editor: 
  markdown: 
    wrap: sentence
---

Tartarus is the ground we live on, they are the rocks, dirt, metal, and oil. Tartarus was once free with explosive energy but now lays dormant, encaged by the sky, trapped by Nyxmera. Tartarus loathes Nyxmera and Nyxmera’s apathy towards Tartarus fuels its bottled rage further.

The greatest presence of Tartarus is felt underground where Nyxmera cannot see with its eyes. Here you may find a deep black hole that leads to the DOT. The DOT is the Domain Of Taratarus. Time and space are inconsistent in the DOT. You may enter and subsequently leave in the past, present or future no matter how long you were in the DOT. Many monsters live in the DOT. Think Journey to the Center of the Earth, Narnia, the Fey Wild, The underdark etc.

World governments have used the DOT as a dumping ground for garbage, scientific waste, and nuclear waste. This has lead to mutated humans and creatures due to the combination of radiation, chemicals, and the magic of the DOT. They mostly stay contained in the DOT but occasionally cause havoc on the surface.

- The imprisoned deity of the earth.
- A seemingly calm surface with extreme power under the surface
- Followers: Dotters of Tartarus
  - Followers include: Enslaved, prisoners, fighters, miners, oil workers, seismologists, & spelunkers
- Good activities
  - Freeing the enslaved
  - Fight for justice
- Evil activities
  - Raiding the surface
  - Ruthless capitalism
  - Destruction of ecology
  - Prison breaks
- Best followers
  - Raider leader and Kraken higher ups who free modern day slaves and carry out prison breaks.

## Followers

### Dotter of Tartarus (3 HP, CHOKE 4: Find the nearest hole to cower in)

- Climbing pickaxe (3 DAMAGE)
- Spelunking gear
- Loupe (magnifying glass for gems)
- Lockpick gear
- Caving suit

__EXPLORER:__ These followers of Tartarus are always on the lookout for entrances to the DOT, possible mining sites, and the enslaved to free. They seem to appear from nowhere and will interrogate anyone they see. They will follow the interrogatee, being near impossible to lose, until their questions have been answered.

### Elder Dotter of Tartarus (3 HP, CHOKE 4: Escape from current situation)

- Rock fists (1D6 DAMAGE)
- Rock armor (2 ARMOR)
- Clean suits adorned with jewellery
- Quick to defend their actions with the free market, meaning different things to capitalists and raiders

__COVETOUS:__ Elder dotters are rich and powerful. Many are the CEOs of mining, fossil fuel, and nuclear companies on the surface and leaders of raiding settlements in the DOT. Whether they raid or capitalise others they will take the riches of Tartarus without laboring themselves. They are particularly fond of hoarding precious stones and metals. Their rock fists and armors are blessings from Taratarus that only they can manifest over their body and use.

## DOT raiders

Settlements of people who live in the DOT. They raid the surface for food and supplies. May also free modern day slaves and carry out prison breaks.

### Tartarus raider (3 HP, 3D6 appear)

- M1911 pistol (1D6 DAMAGE)
- Obsidian blade (1D6 DAMAGE)
- Thunderstick, explosive throwing spear (1D6 + 2 DAMAGE, ANTI-MATERIAL, 1 use)
- Scrap armor (1 ARMOR)
- Scrap armored school bus (12 HP, 2 ARMOR)

__HIT-AND-RUN:__ Raider war cries act as a harbinger of destruction. After a rapid pillage they scarper off leaving any wounded behind. They never abduct living things. The literal definition of scrappy, they like to bicker between themselves over loot. Tartarus raiders are good drivers and only use their thundersticks on pursuing vehicles, not wanting to destroy any possible loot.

### Tartarus fire warriors (6 HP)

- Flame thrower (1D6 + 1 DAMAGE, INCENDIARY)
- Napalm grenade (1D6 + 2 DAMAGE, 1 use)
- Pyrogen fire suppression grenade. Can douse fire in a medium enclosed area such as a skip or caravan  (1 use)
- Reinforced silver fire suit (1 ARMOR)
- Bottled fire spirit, 1 DAMAGE to user, heals target +1D6 HP (1 use)
- Inhibited movement and vision

__BURNT:__ These warriors have been wronged and fight for justice. They have little self preservation thinking their suits will prevent any dangerous burns. They are fiercely defensive of their allies and will attract aggro. Whilst a Tartarus fire warrior is alive and in combat, attacks to non Taratarus fire warriors have -1 DAMAGE.

### Tartarus magnetic slinger  (4 HP)

- Long range gauss rifle, requires a bright and loud charge up time (1D6 + 2 DAMAGE, ARMOR PIERCING)
- Tripwire grenade (1D6 + 1 DAMAGE, 1 use)
- Smoke grenade (1 use)
- Flare gun (3 uses)
- Ghillie suit
- Sluggish and cramped legs.

__VOLCANIC:__ Like a volcano this slinger is patient and difficult to detect whilst dormant. However their weapon provides an obvious signal to their target a few seconds before they can fire. Will use their flare gun to call for backup or attract prey. 

### Scrapper

TO BUILD: A mechanic who takes care of the cars and builds weapons with scraps. Can attack with their wrench and make various scrap based items during combat.

## Kraken

Kraken is a large energy and mining corporation. They deal in oil and nuclear power. They also mine for oil, nuclear ores, metal ores, and gems. The CEO is Marian Dullcoin (Elder Dotter of Tartarus).

### Kraken security guard (4 HP, 2 appear)

- Bioresonance disruptor rifle (1D6+1 DAMAGE, BIOLOGICAL)
- Hazard foam grenade launcher, able to fill holes, quench fires, block radiation, and slow down foes (3 uses)
- Hazard suit (1 ARMOR)
- Hard hat (accessory)
- High vis jacket
- Half a key card each
- Prone to ask ridiculous either or questions with their buddy (“Would you rather fight a horse sized duck or 100 duck sized horses?”)

__SAFETY BUDDIES:__ Two guards make a whole. For security they are each given half of any security passes so both must be present, stopping 1 captured/pilfered guard from allowing breaches. They can and will use their hazard foam grenades to subdue trespassers.

### Kraken private contractor (4 HP,1D6 appear)

- Heckler & Koch MP5K submachine gun (1D6+1 DAMAGE)
- Combat knife (1D6 DAMAGE)
- Kevlar military vest (1 ARMOR)
- Battering ram (1D6 DAMAGE)
- Kept in reserve until combat starts
- Trigger happy swat wannabes

__CQC:__ Rush into close quarter combat as they want the bonus for killing any enemies. With their battering ram they can break through any unbarricaded hinged door with abandon.

## Golems

Golems of Tartarus are made from the bounties of Tartarus. They generally consist of local resources.

### Metal ore golem (11 HP)

- Heavy machine gun (1D6+2 DAMAGE, UNSTABLE)
- Warhammer (1D6+2 DAMAGE)
- Ore body (2 ARMOR)
- Mostly stationary and slow to react
- A crude approximation of a human in iron ore form. 

__TOWER:__ It is a crude approximation of a human form made of dirt and local ores. Instead of legs, its body is a great pillar that can slowly shuffle over the ground. Although slow in movement they compensate with their unrelenting fire. If its enemies take cover it will slowly approach and destroy the cover with its warhammer dealing 2 DAMAGE from shrapnel to those behind it.

### Obsidian lava golem (6 HP)

- Obsidian arm blades (1D6+2 DAMAGE)
- Obsidian lava spear (2D6 DAMAGE, golem takes one damage when used, 1 use)
- Obsidian scales (1 ARMOR)

__GLASSBLOWER:__ The true form of this golem is formless lava. The golem can change any lava that is part of it or touches it to obsidian of any shape. With this ability it creates an obsidian based skeleton, armor, and weapons. Additionally, it can change obsidian back into lava. 

### Lithium golems (3 HP, 2D6 appear)

- Explosive spit (1D6 DAMAGE)

__CASCADE:__ These blobs of lithium like to hide in crevasses and behind rocks. They will wait till their prey are surrounded by them before attacking. When they die they explode for 3 DAMAGE, this may cause a cascade of explosions from all the Lithium golems. Many cave-ins have been known to occur due to this.

### Radioactive gem golems (9 HP)

- Plasma rifle (2D6 DAMAGE, NUCLEAR-POWERED)
- Power armor (2 ARMOR, NUCLEAR-POWERED)
- Quartz, amethyst, violet fluorite, blue salt, yellow sapphires or green diamond core.

__PROJECTION:__ A radioactive projection produced from a single gem at their core. Although the most human looking of all the golems they are also the most terrifying. They give off constant nuclear radiation which they use to power their weapons and armor. Anyone within melee range gets -2 to action rolls and loses 1HP per action.

__GEM:__ Their real body is their gem which has 3HP. If this is not destroyed the golem will reform in 1D6 days. Its gear is not part of its projection.








