---
title: "AVOW: Assassinating the Veiled at the Opulent Wedding"
editor: 
  markdown: 
    wrap: sentence
---

## Dilemma

Team chooses one of 2 options:

- Hired by Gaians to stop assassination attempts during the wedding.
- Hired by [Camera Obscura](/Nyxmera/Camera_Obscura.qmd) to assassinate the 2 brides. Camera Obscura agents are known as shutterbugs.

Two very rich and influential brides are to marry at a very opulent wedding. 
One bride is called River Dullcoin, an [ELDER DOTTER OF TARTARUS](/Tartarus/Dotters.qmd#elder_dotter). She is the daughter of Marian Dullcoin, CEO of [Kraken](/Tartarus/Kraken.qmd).
The second bride is River Ox, a [PROTEAN CAPTAIN](/Proteus/Followers.qmd#protean_captain).
They are a famous and well renowned figure skating coach, many of her skaters having won golds in the winter Olympics.

The wedding takes place at a extravagant estate. It is by the [Ruby River](https://en.wikipedia.org/wiki/Ruby_River) in southwestern Montana.

## Preventing assasination

FIST must stop the Camera Obscura shutterbugs.
The players will be told by the Gaians when the assassinations will occur but have no further intel.
The players can gather intel and should try to figure out who the shutterbugs are and their modes of assassination.

The team will be informed to not capture or stop the shutterbugs until each of their scheduled events.
Otherwise an unknown less cautious backup shutterbug ([NYXMERA DARK TROPPER](/Nyxmera/Troops.qmd#nyxmera_dark_tropper)) will appear in their place.

The team must do this covertly without the wedding guests, including the brides, realising what they are doing or that assassination attempts are occurring.
The guards of the wedding have been told and will recognise and help the FIST team.

### Rewards

Depending on how well they accomplished the mission they will get up to 3 rewards. Some demerits include if they were spotted, and if they only saved one bride.

1. Warhammer (1D6+1 DAMAGE, HEAVY, ROOTS)
2. 1D6 bulletproof vests (1 ARMOR)
3. Medical supplies (1D6 medkits, +1D6+TAC HP)

__HEAVY__ weapon tag: This thing is too big to be called a weapon. Once per mission, take +3 on a FORCEFUL roll that involves this weapon.

__ROOTS__ weapon tag: Once per mission, after hitting a target roots will explosively grow from the impact site. This can weaken cracked structures, bind objects or individuals together, and various other effects.

## Carrying out the assassinations

The player team will get the chance to kill the brides in their consummation bedroom. They must do this before they have started consummation of their marriage.

However, they will also need to stop the 2 assassination attempts at the ceremony and dinner. Due to the Camera Obscura rules they cannot harm, kill, or kidnap the other "shutterbugs".

The Camera Obscura client wants the assassination to occur at 1 of three times.
They will not pay if it occurs outside of these times.
Additionally, Camera Obscura will not pay shutterbugs who harm, kill, or kidnap any of the other guests as there are many rich and powerful people.

### Rewards

Depending on how well they accomplished the mission they will get up to 3 rewards. Some demerits include if they broke Camera Obscura rules, and if they only killed one bride.

1. [Steyr SSG 69](https://en.wikipedia.org/wiki/Steyr_SSG_69) bolt-action sniper rifle (1D6+2 DAMAGE, HUD)
2. Combat knife (1D6 DAMAGE, LUCKY)
3. 1D6 smoke grenades & 1D6 frag grenades (1D6+1 DAMAGE)

__HUD__ weapon tag: Scans hostiles. When you kill something new, the referee will tell you a useful fact about it.

__LUCKY__ weapon tag: Rolling an ultra success while attacking with this weapon grants the user one WAR DIE.

## Wedding events

The wedding is broken into several events. 
Only the Ceremony, Dinner, and Consummation will have an assassination attempt.

All the events take place on the estate grounds.
No maps of the estate are given so you can create your own vision with the prompts in the below descriptions.

### Rehearsal dinner

The rehearsal dinner takes place the evening before the actual wedding. It will be in the same ball room described in the [Dinner](#dinner_event) section. No assassination will take place but it is a prime time for the players to carry out some intel gathering on the hired shutterbugs.

### Ceremony

The ceremony takes place outside in a area flanked by the Ruby River and a rock garden full of beautiful geodes.

[THE KING](/Nyxmera/Camera_Obscura.qmd#the_king) is using one of their personas (Aurelia Blaine) to attend the wedding as an invited guest.
During the rehearsal dinner she will will steal River's wedding ring. THE KING will attempt to set their curse on River and the wedding ring.
They will entertain and perform card tricks for the brides to get close to them.

Clue: Players will overhear one of the bridesmaids saying they have lost River's ring as they recruit help from the other bridesmaids.

If not stopped the couple will turn into gold as Ruby puts River's ring on during the ceremony.

### Figure skating break

After the ceremony the wedding party will move onto an outdoor skating rink.
Here, River's past and present skaters (all guests to the wedding) will provide an amazing show.

Ask each of your players for a name of one of the skaters, then ask them for a name and description of a figure skating move.
Give a WAR DIE to the player with the skater and move the table agrees is best.

### Dinner {#dinner_event}

The dinner takes place in a large ball room dominated by a central large ornate water fountain sculpted from rock.
On one side of the room lay the tables for the dinner.
On the other is a large stage and dance floor.

The dinner will consist of the speeches followed by the main meal.
The brides will then cut their wedding cake which will lead to their first dance.

The designated shutterbug is [THE ANTIDOTER](/Nyxmera/Camera_Obscura.qmd#the_antidoter). 
They have poisoned all the food with the first part of their poison and the entire wedding cake with the second part.

Clue: During the dinner the 2 brides will leave and a fog machine will go off before the dancing commences. This is the work of the THE ANTIDOTER.

If not stopped the couple will die of heart attacks during their first dance.

### Entertainment

After watching the first dance, the guests will join in the festivities with drinking and dancing.
Various famous bands will play on the stage.

Unsurprisingly, Ruby is a big fan of Rock and Metal bands.
Ask your players for some fictional bands that will be performing.
Give a WAR DIE to the player with band name the table agrees is the best.

### Consummation

At the end of the night the newly wedded couple will leave the ball room and go to their private building within the estate.
This building is secluded on top of a rock outcropping.
It is flanked by the river and surrounding forest.
One side of the building is a large glass wall that overlooks the Ruby River.

If the players are assassinating they must do so after the couple have entered the building but before they have consummated the wedding.
In this case the building is guarded by 4 [KRAKEN SECURITY GUARDS](/Tartarus/Kraken.qmd#kraken_guard).
The team will succeed if they kill both brides and partially succeed if they kill at least one.

If the players are stopping the assassinations, the last shutterbug is the [THE SILHOUETTE](/Nyxmera/Camera_Obscura.qmd#the_silhouette). They will be parked a few miles away as they send in their 4 [SILHOUETTE SHADOW CLONES](/Nyxmera/Camera_Obscura.qmd#silhouette_shadow_clone) to storm the private building.
The clones will try to stealthily enter but are not afraid to enter a gunfight.
The team will succeed if they save both brides and partially succeed if they save at least one.