---
title: "SACK: Schematic Acquisition Crime against Kraken"
editor: 
  markdown: 
    wrap: sentence
---

Gaian forces want schematics for a new solar panel technology. These are being held by the energy company “Kraken” run by the CEO “Marian Dullcoin”, an elder dotter of Tartarus. Extract this from their R&D facility in their private industrial estate on the Spanish island of Mallorca.

Extraction on small island Cabrera.

Reward: Provided intel says there is a prototype plasma cutter pistol being developed in the R&D facility. Unstable the Gaians know how to finalise it (remove unfinished) with previous gathered intel.

Plasma cutter (1D6+2 DAMAGE, ROCKCUTTER, UNFINSIHED)
ROCKCUTTER: Makes clean line cuts that can go through flesh, bone, and rock. Purpose made to not damage gems and metals. Side effect is that it cannot damage plant based materials.
UNFINISHED: When fired, roll a D6. If your roll is equal to or less than the number of times you have used the weapon it fails and will no longer work till repaired and finished.
