---
title: "Starvatars"
editor: 
  markdown: 
    wrap: sentence
---

A Starvatar of Nyxmera is the light of a star. When it exists the star’s light can no longer be seen in the night sky as it now exists as a hard light being. Each Starvatar will take the name of its star or constellation.

They are humanoid like being made of the night sky. They are pitch black solid with twinkling lights covering their body. Their legs and arms taper down to points like the human depiction of a star on paper. Invisible digits allow them to handle anything a human could including guns.

All Starvatars of Nyxmera look nearly identical except for their heads. These are in the shape of something related to the human mythology of their star or the constellation it belongs to. On this head is one bright light, the star’s light they use as an eye. Examples of head shapes include:

- Zodiac: Leo = Lion, Cancer = Crab , Gemini = Twins, Taurus = bull, Aries = Ram, Pisces = Fish, Aquarius = water carrier, Capricorn =  Sea goat, Sagittarius = Centaur, Scorpio = scorpion, Libra = Scales, Virgo =  Maiden.
- Bear head from Ursa major and minor

Powerful Starvatars can create temporary structures made of hard light

### Stavatar of Nyxmera {#starvatar}

(9 HP)

- Starlight rifle (1D6 + 2 DAMAGE, MEDICAL)
- Starlight spear (1D6 + 2 DAMAGE, UNSTABLE)
- Hard light armor (2 ARMOR)

__SHADOWMAKER:__ The star avatar’s body is that of the night sky. The shape of its head matches the mythology of the star or constellation it comes from. Upon this head is one eye made from the light of its star. It casts a great light from its eye and body. However shadows caused by this are irrationally dark and cannot be illuminated by other lights.

### Purple Moon of Nyxmera

- 
- A humanoid of night sky larger than a blue whale.
- Its head is a purple crated orb, the purple moon.


__VOYEUR__: Depictions of the past show the purple moon in the night sky. 
Now it perpetually lives as the ultimate representation of Nyxmera.
None can question its authority within the suns of Nyxmera and few can match its power outside.
It lives in its massive estate filled with theatres, cinemas, libraries, rooms full of TVs.
Only the best are allowed to entertain the Purple Moon, and only the richest can join the viewing.
They love sowing drama and comedy, having taken to trolling on elite chat boards.
The purple moon can see anything and everything bathed by the Grey Moon's light.
