---
title: "DOT raiders"
editor: 
  markdown: 
    wrap: sentence
---

Settlements of people who live in the DOT. They raid the surface for food and supplies. May also free modern day slaves and carry out prison breaks.

## TARTARUS RAIDER {#raider}

(3 HP, 2D6 appear)

- [M1911](https://en.wikipedia.org/wiki/M1911_pistol) pistol (1D6 DAMAGE)
- Obsidian blade (1D6 DAMAGE)
- Thunderstick, explosive throwing spear (1D6 + 2 DAMAGE, ANTI-MATERIAL, 1 use)
- Scrap armor (1 ARMOR)
- Scrap armored school bus (12 HP, 2 ARMOR)

__HIT-AND-RUN:__ Raider war cries act as a harbinger of destruction. After a rapid pillage they scarper off leaving any wounded behind. They never abduct living things. The literal definition of scrappy, they like to bicker between themselves over loot. Tartarus raiders are good drivers and only use their thundersticks on pursuing vehicles, not wanting to destroy any possible loot.

__ANTI-MATERIAL__ weapon tag: Deals double DAMAGE to vehicles and structures; cumbersome to carry around.

## TARTARUS MUTANT {#tartarus_mutant}

(5 HP)

- [MAS-36](https://en.wikipedia.org/wiki/MAS-36_rifle) bolt-action rifle (1D6+1 DAMAGE)
- Tattered clothing barely covering their portfolio of scars
- Faint blue/green glow from their veins
- No two mutants are the same, the below mutations are left vague for the referee's and/or players' imagination to fill

__ADAPTED:__ These were once normal humans who lived in the settlements of the DOT. They have survived longer than most and so have been mutated from the pervasive chemicals and radiation. When one appears roll 2D6 to determine which of the two following mutations they have (reroll duplicates).

1. Exoskeleton (2 ARMOR)
2. Lethal arms (1D6 + 1 DAMAGE)
3. Powerful strides and jumps
4. Enhanced sense
5. Extra appendage
6. TARTARUS MUTANT gets a total of 3 of the other options

__MELTDOWN (BOSS MOVE):__ As a last resort and with a well choreographed lead up the TARTARUS MUTANT can cause itself to explode. It dies whilst dealing 2D6 DAMAGE to everything within 20 feet.

## TARTARUS FIRE WARRIORS {#fire_warrior}

(6 HP)

- Flame thrower (1D6 + 1 DAMAGE, INCENDIARY)
- Napalm grenade (1D6 + 2 DAMAGE, 1 use)
- Pyrogen fire suppression grenade. Can douse fire in a medium enclosed area such as a skip or caravan  (1 use)
- Reinforced silver fire suit (1 ARMOR)
- Bottled fire spirit, 1 DAMAGE to user, heals target +1D6 HP (1 use)
- Inhibited movement and vision

__BURNT:__ These warriors have been wronged and fight for justice. They have little self preservation thinking their suits will prevent any dangerous burns. They are fiercely defensive of their allies and will attract aggro. Whilst a Tartarus fire warrior is alive and in combat, attacks to non Taratarus fire warriors have -1 DAMAGE.

## TARTARUS MAGNETIC SLINGER {#magnetic_slinger}

(4 HP)

- Long range gauss rifle, requires a bright and loud charge up time (1D6+2 DAMAGE, ARMOR PIERCING)
- Tripwire grenade (1D6 + 1 DAMAGE, 1 use)
- Smoke grenade (1 use)
- Flare gun (3 uses)
- Ghillie suit
- Sluggish and cramped legs.

__VOLCANIC:__ Like a volcano this slinger is patient and difficult to detect whilst dormant. However their weapon provides an obvious signal to their target a few seconds before they can fire. Will use their flare gun to call for backup or attract prey.

__ARMOR-PIERCING__ weapon tag: Attacks with this weapon ignore ARMOR bonuses granted by physical means.

## SCRAPPER {#scrapper}

TO BUILD: A mechanic who takes care of the cars and builds weapons with scraps. Can attack with their wrench and make various scrap based items during combat.